### ISSUE TITLE
Wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by aglushkov** [shrinerb/shrine#384]
### Brief Description
**Metadata_attributes** plugins `#assign` method now accepts two arguments in version 2.17.
**Parsed_json** plugins `#assign` still has single argument. 

### Expected behavior
Should be no errors when using both plugins

### Actual behavior
Error raised

### Simplest self-contained example code to demonstrate issue
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'activerecord'
  gem 'sqlite3'
  gem 'shrine', '2.17'
  gem 'down'
end

require "active_record"
require "shrine"
require "shrine/storage/file_system"
require "tmpdir"
require "down"

Shrine.plugin :activerecord
Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new(File.join(Dir.tmpdir, "shrine")),
  store: Shrine::Storage::FileSystem.new(File.join(Dir.tmpdir, "shrine")),
}

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.connection.create_table(:posts) { |t| t.text :image_data }

class MyUploader < Shrine
  plugin :parsed_json
  plugin :metadata_attributes
end

class Post < ActiveRecord::Base
  include MyUploader::Attachment.new(:image)
end

Post.new(image: Down.download("https://twin.github.io/images/logo.png"))

# Traceback (most recent call last):
#   13: from test.rb:40:in `<main>'
#   12: from /activerecord-5.2.3/lib/active_record/inheritance.rb:66:in `new'
#   11: from /activerecord-5.2.3/lib/active_record/inheritance.rb:66:in `new'
#   10: from /activerecord-5.2.3/lib/active_record/core.rb:315:in `initialize'
#    9: from /activemodel-5.2.3/lib/active_model/attribute_assignment.rb:35:in `assign_attributes'
#    8: from /activerecord-5.2.3/lib/active_record/attribute_assignment.rb:23:in `_assign_attributes'
#    7: from /activemodel-5.2.3/lib/active_model/attribute_assignment.rb:43:in `_assign_attributes'
#    6: from /activemodel-5.2.3/lib/active_model/attribute_assignment.rb:43:in `each'
#    5: from /activemodel-5.2.3/lib/active_model/attribute_assignment.rb:44:in `block in _assign_attributes'
#    4: from /activemodel-5.2.3/lib/active_model/attribute_assignment.rb:51:in `_assign_attribute'
#    3: from /activemodel-5.2.3/lib/active_model/attribute_assignment.rb:51:in `public_send'
#    2: from /shrine-2.17.0/lib/shrine/attachment.rb:49:in `block in define_attachment_methods!'
#    1: from /shrine-2.17.0/lib/shrine/plugins/metadata_attributes.rb:22:in `assign'
# /shrine-2.17.0/lib/shrine/plugins/parsed_json.rb:10:in `assign': wrong number of arguments (given 2, expected 1) (ArgumentError)

```
### System configuration
**Ruby version**: 2.6.0
**Shrine version**: 2.17

**Comment by janko** [comment]
Thanks for reporting, I'll push a fix shortly and release a new version.
