### ISSUE TITLE
Removing attachments does not work with metadata_attribute plugin 

### ISSUE THREAD

**Issue by aglushkov** [shrinerb/shrine#421]
### Brief Description
When using metadata_attribute plugin it is impossible to remove attachment by assigning `nil`

### Expected behavior
No errors

### Actual behavior
Error raised
```
gems/shrine-3.0.0/lib/shrine/plugins/metadata_attributes.rb:41:in `block in metadata_attributes': undefined method `[]' for nil:NilClass (NoMethodError)
```

### Simplest self-contained example code to demonstrate issue
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'activerecord'
  gem 'sqlite3'
  gem 'shrine'
  gem 'down'
end

require "active_record"
require "shrine"
require "shrine/storage/file_system"
require "tmpdir"
require "down"

Shrine.plugin :activerecord
Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new(File.join(Dir.tmpdir, "shrine")),
  store: Shrine::Storage::FileSystem.new(File.join(Dir.tmpdir, "shrine")),
}

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.connection.create_table(:posts) do |t|
  t.text :image_data
  t.text :filename
end

class MyUploader < Shrine
  plugin :metadata_attributes, filename: 'filename'
end

class Post < ActiveRecord::Base
  include MyUploader::Attachment.new(:image)
end

post = Post.new(image: Down.download("https://twin.github.io/images/logo.png"))
post.image = nil

#Traceback (most recent call last):
#  12: from ../shrine_metadata_issue.rb:43:in `<main>'
#  11: from /home/aglushkov/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/shrine-3.0.0/lib/shrine/plugins/model.rb:41:in `block in define_model_methods'
#  10: from /home/aglushkov/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/shrine-3.0.0/lib/shrine/plugins/model.rb:114:in `model_assign'
#   9: from /home/aglushkov/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/shrine-3.0.0/lib/shrine/attacher.rb:72:in `assign'
#   8: from /home/aglushkov/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/shrine-3.0.0/lib/shrine/attacher.rb:94:in `attach_cached'
#   7: from /home/aglushkov/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/shrine-3.0.0/lib/shrine/attacher.rb:114:in `attach'
#   6: from /home/aglushkov/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/shrine-3.0.0/lib/shrine/attacher.rb:216:in `change'
#   5: from /home/aglushkov/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/shrine-3.0.0/lib/shrine/plugins/model.rb:123:in `set'
#   4: from /home/aglushkov/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/shrine-3.0.0/lib/shrine/plugins/model.rb:129:in `write'
#   3: from /home/aglushkov/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/shrine-3.0.0/lib/shrine/plugins/metadata_attributes.rb:28:in `column_values'
#   2: from /home/aglushkov/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/shrine-3.0.0/lib/shrine/plugins/metadata_attributes.rb:36:in `metadata_attributes'
#   1: from /home/aglushkov/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/shrine-3.0.0/lib/shrine/plugins/metadata_attributes.rb:36:in `each'
#/home/aglushkov/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/shrine-3.0.0/lib/shrine/plugins/metadata_attributes.rb:41:in `block in metadata_attributes': undefined method `[]' for nil:NilClass (NoMethodError)
```

### System configuration
**Ruby version**: 2.6.5
**Shrine version**: 3.0.0

**Comment by janko** [comment]
Thanks for the report. I'll push a fix shortly and release a new patch version.

**Comment by aglushkov** [comment]
Thanks a lot,  it was fastest fix ever :+1:
