### ISSUE TITLE
Shrine.derivatives iteration reached an end

### ISSUE THREAD

**Issue by cilim** [shrinerb/shrine#440]
### Brief Description
Unable to save record with `image_data` when `:processing` and `:versions` plugins substituted with `:derivatives` plugin .

### Expected behavior
Image would be saved to S3 and derivatives created alongside it.

### Actual behavior
Request broke on line: `@photo.image_derivatives! if @photo.image_changed?` with error:
```
StopIteration (iteration reached an end)
```

### Simplest self-contained example code to demonstrate issue
```
class ImageUploader < Shrine
  plugin :upload_endpoint if Configuration.upload_endpoint?

  plugin :upload_options, store: { acl: 'public-read', cache_control: 'public, max-age=604800' }
  plugin :url_options, store: { public: true }
  plugin :determine_mime_type
  plugin :pretty_location
  plugin :validation_helpers
  plugin :derivatives

  Attacher.validate do
    validate_size 1..5 * 1024 * 1024
    validate_mime_type_inclusion %w[image/jpg image/jpeg image/png],
                                 message: 'must be .jpg, .jpeg or .png'
    validate_extension_inclusion %w[jpg jpeg png], message: 'extension must be .jpg, .jpeg or .png'
  end

  Attacher.derivatives_processor do |original|
    pipeline = ImageProcessing::MiniMagick.source(original)

    large = pipeline.resize_to_limit!(1200, 1200)
    medium = pipeline.resize_to_limit!(600, 600)
    small = pipeline.resize_to_limit!(300, 300)
    thumbnail = pipeline.resize_to_limit!(48, 48)
    preloader = pipeline.resize_to_limit!(8, 8)

    { large: large, medium: medium, small: small, thumbnail: thumbnail, preloader: preloader }
  end
end

# Controller
def create
  @photo = Photo.new(image_params)
  if @photo.valid
    @photo.image_derivatives! if @photo.image_changed?
    @photo.save
  end
  
  respond_with @photo
end
```

### System configuration
**Ruby version**: 2.6.5

**Shrine version**: 3.0.1 (tried also with 3.2.0 - same error)

**Comment by janko** [comment]
You need to include the `versions_compatibility: true` flag to allow the `derivatives` plugin to read the "versions" format.

```rb
plugin :derivatives, versions_compatibility: true
```

Eventually you'll want to migrate existing attachment data to the new format, so that you can remove the flag. This is explained in the [upgrading guide](https://shrinerb.com/docs/upgrading-to-3#versions).

**Comment by cilim** [comment]
Thanks for the fast reply!

I changed the `ImageUploader`. This is how it's set up now:

```
class ImageUploader < Shrine
  plugin :upload_endpoint if Configuration.upload_endpoint?

  plugin :upload_options, store: { acl: 'public-read', cache_control: 'public, max-age=604800' }
  plugin :url_options, store: { public: true }
  plugin :determine_mime_type
  plugin :pretty_location
  plugin :default_url
  plugin :validation_helpers
  plugin :derivatives, versions_compatibility: true

  Attacher.default_url do |_options|
    "/missing_#{name}.svg"
  end

  Attacher.validate do
    validate_size 1..5 * 1024 * 1024
    validate_mime_type_inclusion %w[image/jpg image/jpeg image/png],
                                 message: 'must be .jpg, .jpeg or .png'
    validate_extension_inclusion %w[jpg jpeg png], message: 'extension must be .jpg, .jpeg or .png'
  end

  Attacher.derivatives_processor do |original|
    pipeline = ImageProcessing::MiniMagick.source(original)

    large = pipeline.resize_to_limit!(1200, 1200)
    medium = pipeline.resize_to_limit!(600, 600)
    small = pipeline.resize_to_limit!(300, 300)
    thumbnail = pipeline.resize_to_limit!(48, 48)
    preloader = pipeline.resize_to_limit!(8, 8)

    { large: large, medium: medium, small: small, thumbnail: thumbnail, preloader: preloader }
  end

  class Attacher
    def promote(*)
      create_derivatives # creates automatically and preserves usual :versions plugin behaviour

      super
    end
  end
end
```

unfortunately, the same error is raised. If I'm analysing the Shrine source code correctly, I believe that it tries to download the original image and create derivatives, but the thing is that the file is not uploaded to S3 at the moment of the record creation. There's nothing to download yet...

**Comment by janko** [comment]
Can you also post the contents of your Shrine initializer? The `Attacher#promote` method won't be called unless a cached file is attached. It doesn't need to be on S3 storage for it to be downloadable, it can be cached to any other storage.

I was not able to reproduce the issue, I tried so with the following self-contained script:

```ruby
require "shrine"
require "shrine/storage/memory"
require "image_processing/mini_magick"
require "active_record"
require "down"

ActiveRecord::Base.establish_connection(
  adapter:  "sqlite3",
  database: ":memory:",
)

ActiveRecord::Base.connection.create_table :photos do |t|
  t.text :image_data
end

Shrine.storages = {
  cache: Shrine::Storage::Memory.new,
  store: Shrine::Storage::Memory.new,
}

Shrine.plugin :activerecord

class ImageUploader < Shrine
  plugin :upload_endpoint

  plugin :upload_options, store: { acl: 'public-read', cache_control: 'public, max-age=604800' }
  plugin :url_options, store: { public: true }
  plugin :determine_mime_type
  plugin :pretty_location
  plugin :default_url
  plugin :validation_helpers
  plugin :derivatives, versions_compatibility: true

  Attacher.default_url do |_options|
    "/missing_#{name}.svg"
  end

  Attacher.validate do
    validate_size 1..5 * 1024 * 1024
    validate_mime_type_inclusion %w[image/jpg image/jpeg image/png],
                                 message: 'must be .jpg, .jpeg or .png'
    validate_extension_inclusion %w[jpg jpeg png], message: 'extension must be .jpg, .jpeg or .png'
  end

  Attacher.derivatives_processor do |original|
    pipeline = ImageProcessing::MiniMagick.source(original)

    large     = pipeline.resize_to_limit!(1200, 1200)
    medium    = pipeline.resize_to_limit!(600, 600)
    small     = pipeline.resize_to_limit!(300, 300)
    thumbnail = pipeline.resize_to_limit!(48, 48)
    preloader = pipeline.resize_to_limit!(8, 8)

    { large: large, medium: medium, small: small, thumbnail: thumbnail, preloader: preloader }
  end
end

class Photo < ActiveRecord::Base
  include ImageUploader::Attachment(:image)
end

file = Down.download("https://upload.wikimedia.org/wikipedia/commons/3/36/Hopetoun_falls.jpg")

photo = Photo.new(image: file)

if photo.valid?
  photo.image_derivatives! if photo.image_changed?
  photo.save
end
```

When I ran the above script, there were no errors, and the derivatives were stored successfully.

The exception is originating from the `Shrine.map_derivative` method, I'm wondering what input causes it to fail 🤔. Could you include the backtrace of the exception? Also, could you place the following `p` statements and post the output:

```rb
class ImageUploader < Shrine
  # ...
  def self.derivatives(*args, &block)
    p args
    super
  end

  class Attacher
    private
    def map_derivative(*args, &block)
      p args
      super
    end
  end
end
```

**Comment by cilim** [comment]
> Can you also post the contents of your Shrine initializer?

Sure thing!:
```
# frozen_string_literal: true

require 'shrine'
require 'shrine/storage/s3'
require "shrine/storage/memory"

s3_options = {
  bucket: Rails.application.secrets.aws[:s3][:bucket],
  access_key_id: Rails.application.secrets.aws[:s3][:access_key_id],
  secret_access_key: Rails.application.secrets.aws[:s3][:secret_access_key],
  region: Rails.application.secrets.aws[:s3][:region]
}
s3_options[:stub_responses] = true if Rails.env.development? || Rails.env.test?

if Rails.env.test?
  Shrine.storages = {
    cache: Shrine::Storage::Memory.new,
    store: Shrine::Storage::Memory.new
  }
else
  Shrine.storages = {
    cache: Shrine::Storage::S3.new(prefix: 'cache', **s3_options),
    store: Shrine::Storage::S3.new(**s3_options)
  }
end

Shrine.plugin :activerecord
Shrine.plugin :cached_attachment_data # for retaining the cached file across form redisplays
Shrine.plugin :restore_cached_data # re-extract metadata when attaching a cached file

Shrine.plugin :presign_endpoint
Shrine.plugin :remove_attachment
```

Here's the log output from the local rails server:
```
Started POST "/dashboard/lectures" for ::1 at 2019-12-17 16:00:37 +0100
Processing by Dashboard::LecturesController#create as HTML
  Parameters: {"authenticity_token"=>"token==", "lecture"=>{"title_en"=>"New lecture", "abstract_en"=>"", "poster"=>#<ActionDispatch::Http::UploadedFile:0x00007f999851a750 @tempfile=#<Tempfile:/var/folders/j1/h7vx_wl53rq35ly1yr3184br0000gn/T/RackMultipart20191217-94255-18aakgc.jpg>, @original_filename="fine-header_1024.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"lecture[poster]\"; filename=\"fine-header_1024.jpg\"\r\nContent-Type: image/jpeg\r\n">}, "commit"=>"Create Lecture"}
  Administrator Load (0.5ms)  SELECT "administrators".* FROM "administrators" WHERE "administrators"."id" = $1 ORDER BY "administrators"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
[{}]
   (0.4ms)  BEGIN
  ↳ app/controllers/dashboard/lectures_controller.rb:22:in `create'
  Lecture Create (0.7ms)  INSERT INTO "lectures" ("created_at", "updated_at", "title_i18n", "poster_data") VALUES ($1, $2, $3, $4) RETURNING "id"  [["created_at", "2019-12-17 15:00:37.766021"], ["updated_at", "2019-12-17 15:00:37.766021"], ["title_i18n", "{\"en\":\"New lecture\"}"], ["poster_data", "{\"id\":\"lecture/poster/105ed011688c73de0e39ae95aa6b0d7e.jpg\",\"storage\":\"cache\",\"metadata\":{\"filename\":\"fine-header_1024.jpg\",\"size\":62256,\"mime_type\":\"image/jpeg\"}}"]]
  ↳ app/controllers/dashboard/lectures_controller.rb:22:in `create'
   (0.5ms)  COMMIT
  ↳ app/controllers/dashboard/lectures_controller.rb:22:in `create'
Not notifying due to notify_release_stages :["production", "staging"]
Completed 500 Internal Server Error in 44ms (ActiveRecord: 2.1ms | Allocations: 9349)


Not notifying due to notify_release_stages :["production", "staging"]
  
StopIteration (iteration reached an end):
  
app/uploaders/image_uploader.rb:39:in `promote'
```

and here's the _Framework trace_:
```
shrine (3.2.0) lib/shrine/storage/s3.rb:288:in `peek'
shrine (3.2.0) lib/shrine/storage/s3.rb:288:in `get_object'
shrine (3.2.0) lib/shrine/storage/s3.rb:106:in `open'
shrine (3.2.0) lib/shrine/uploaded_file.rb:265:in `_open'
shrine (3.2.0) lib/shrine/uploaded_file.rb:93:in `open'
shrine (3.2.0) lib/shrine/uploaded_file.rb:146:in `stream'
shrine (3.2.0) lib/shrine/uploaded_file.rb:122:in `download'
shrine (3.2.0) lib/shrine/plugins/derivatives.rb:272:in `process_derivatives'
shrine (3.2.0) lib/shrine/plugins/derivatives.rb:184:in `create_derivatives'
app/uploaders/image_uploader.rb:39:in `promote'
shrine (3.2.0) lib/shrine/attacher.rb:162:in `promote_cached'
shrine (3.2.0) lib/shrine/attacher.rb:145:in `finalize'
shrine (3.2.0) lib/shrine/plugins/activerecord.rb:90:in `activerecord_after_save'
shrine (3.2.0) lib/shrine/plugins/activerecord.rb:43:in `block (2 levels) in included'
activesupport (6.0.1) lib/active_support/callbacks.rb:429:in `instance_exec'
activesupport (6.0.1) lib/active_support/callbacks.rb:429:in `block in make_lambda'
activesupport (6.0.1) lib/active_support/callbacks.rb:264:in `block in conditional'
activesupport (6.0.1) lib/active_support/callbacks.rb:518:in `block in invoke_after'
activesupport (6.0.1) lib/active_support/callbacks.rb:518:in `each'
activesupport (6.0.1) lib/active_support/callbacks.rb:518:in `invoke_after'
activesupport (6.0.1) lib/active_support/callbacks.rb:136:in `run_callbacks'
bugsnag (6.12.2) lib/bugsnag/integrations/rails/active_record_rescue.rb:11:in `run_callbacks'
```

Let me know if I can provide any more info. Thanks!

**Comment by cilim** [comment]
P.S. wanted to make sure, the output is ok:
```
"*****ImageUploader.derivatives args:"
[{}]
"******"
```
```
"*****ImageUploader.derivatives args:"
[{}]
"******"```

**Comment by janko** [comment]
Thanks! I think what's happening is that the main attached file is for some reason empty, could you verify that? It seems that the S3 storage is not handling downloading empty files, so that might be the reason for the `StopIteration` exception, I will definitely fix that issue.

In that case, I'm wondering how come the main file is empty, as it shouldn't have passed the MIME type validation in that case 🤔 Maybe something else read the file object before the upload itself without rewinding it afterwards, which could cause empty content to be uploaded.

**Comment by janko** [comment]
For now, you can try applying the following monkey patch to the S3 storage to get rid of the error:

```rb
module WorkingGetObject
  private
  def get_object(object, params)
    content = object.get(params).body.string

    [[content], content.bytesize]
  end
end

Shrine::Storage::S3.prepend WorkingGetObject
```

**Comment by cilim** [comment]
> Thanks! I think what's happening is that the main attached file is for some reason empty, could you verify that?

Yup, when trying to read the file in `Shrine::Plugins::Derivatives.create_derivatives` I get:
```
StopIteration: iteration reached an end
from /Users/cilim/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/shrine-3.2.0/lib/shrine/storage/s3.rb:288:in `peek'
```

> In that case, I'm wondering how come the main file is empty, as it shouldn't have passed the MIME type validation in that case 

I pried in `Attacher.validate` and both validations return true, but explicitly calling `file.read` raises the `StopIteration` exception.

With the monkey patch I receive an empty string in both cases.

**Comment by janko** [comment]
What about this line in your configuration:

```rb
# ...
s3_options[:stub_responses] = true if Rails.env.development? || Rails.env.test?
# ...
```

That would cause downloading the objects return empty content, as stubs by default don't return any content. If you want a "fast S3" for local development, you should use something like [MinIO](https://shrinerb.com/docs/testing#minio) instead.

If this is not causing the issue you've described, then I would need a self-contained script that reproduces the problem, like the one I posted earlier.

**Comment by cilim** [comment]
It seems I haven't spent too much time on reading the documentation regarding `stub_responses` S3 option 🙈that did it! I also had some other issues, but I believe this was the main culprit.

Thanks a bunch!
