### ISSUE TITLE
Derivatives including original fails with activerecord plugin

### ISSUE THREAD

**Issue by okuramasafumi** [shrinerb/shrine#519]
### Brief Description

I use `derivatives` plugin with `create_on_promote` option. I also use `activerecord` plugin.

When I try to promote an image with `ActiveRecord::Base#save!` method, it fails with `No such file or directory @ rb_sysopen` error. It turned out that it's caused by the derivative including `original` in its return value.

### Expected behavior

I should define the derivative including original.

If it's not the case, it should be documented.

### Actual behavior

It causes an error and it's no documented.

### Simplest self-contained example code to demonstrate issue

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  gem 'activerecord', '6.0.3.4'
  gem 'shrine', '3.3.0'
  gem 'sqlite3'
  gem 'image_processing', '~> 1.8'
end

require 'active_record'
require 'shrine'
require 'shrine/storage/memory'
require 'down'
require 'image_processing/mini_magick'

Shrine.storages = {
  cache: Shrine::Storage::Memory.new,
  store: Shrine::Storage::Memory.new
}

Shrine.plugin :activerecord
Shrine.plugin :derivatives,
  create_on_promote:      true, # automatically create derivatives on promotion
  versions_compatibility: true  # handle versions column format

class MyUploader < Shrine
  Attacher.derivatives do |original|
    pipeline = ImageProcessing::MiniMagick.source(original)

    size_300 = pipeline.resize_to_fill!(300, 300, &:auto_orient)

    { original: original, thumb: size_300 }
  end

end

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.connection.create_table(:posts) { |t| t.text :image_data }

class Post < ActiveRecord::Base
  include MyUploader::Attachment(:image)
end

module TestData
  module_function
  def cached_data
    file = Down.download('https://upload.wikimedia.org/wikipedia/commons/c/ca/1x1.png')
    cached = Shrine.upload(file, :cache, metadata: false)
    cached.metadata.merge!(
      "size" => File.size(file.path),
      "mime_type" => "image/png",
      "filename" => "test.png",
    )
    cached.to_json
  end
end

post = Post.new
post.image = TestData.cached_data
post.save! # => error
```

Output:

```txt
Traceback (most recent call last):
	48: from code.rb:62:in `<main>'
	47: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activerecord-6.0.3.4/lib/active_record/suppressor.rb:48:in `save!'
	46: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:318:in `save!'
	45: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
	44: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:212:in `transaction'
	43: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
	42: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
	41: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
	40: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
	39: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
	38: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
	37: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
	36: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:293:in `block in within_new_transaction'
	35: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:255:in `commit_transaction'
	34: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
	33: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
	32: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
	31: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
	30: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
	29: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:265:in `block in commit_transaction'
	28: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:127:in `commit_records'
	27: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:339:in `committed!'
	26: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:825:in `_run_commit_callbacks'
	25: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:136:in `run_callbacks'
	24: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:517:in `invoke_after'
	23: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:517:in `each'
	22: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:517:in `block in invoke_after'
	21: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:263:in `block in conditional'
	20: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:428:in `block in make_lambda'
	19: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:428:in `instance_exec'
	18: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/shrine-3.3.0/lib/shrine/plugins/activerecord.rb:43:in `block (2 levels) in included'
	17: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/shrine-3.3.0/lib/shrine/plugins/activerecord.rb:90:in `activerecord_after_save'
	16: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/shrine-3.3.0/lib/shrine/attacher.rb:145:in `finalize'
	15: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/shrine-3.3.0/lib/shrine/attacher.rb:162:in `promote_cached'
	14: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/shrine-3.3.0/lib/shrine/plugins/derivatives.rb:165:in `promote'
	13: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/shrine-3.3.0/lib/shrine/plugins/derivatives.rb:201:in `create_derivatives'
	12: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/shrine-3.3.0/lib/shrine/plugins/derivatives.rb:218:in `add_derivatives'
	11: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/shrine-3.3.0/lib/shrine/plugins/derivatives.rb:245:in `upload_derivatives'
	10: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/shrine-3.3.0/lib/shrine/plugins/derivatives.rb:484:in `map_derivative'
	 9: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/shrine-3.3.0/lib/shrine/plugins/derivatives.rb:584:in `map_derivative'
	 8: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/shrine-3.3.0/lib/shrine/plugins/derivatives.rb:584:in `inject'
	 7: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/shrine-3.3.0/lib/shrine/plugins/derivatives.rb:584:in `each'
	 6: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/shrine-3.3.0/lib/shrine/plugins/derivatives.rb:587:in `block in map_derivative'
	 5: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/shrine-3.3.0/lib/shrine/plugins/derivatives.rb:602:in `map_derivative'
	 4: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/shrine-3.3.0/lib/shrine/plugins/derivatives.rb:246:in `block in upload_derivatives'
	 3: from /Users/okuramasafumi/.gem/ruby/2.7.2/gems/shrine-3.3.0/lib/shrine/plugins/derivatives.rb:258:in `upload_derivative'
	 2: from /Users/okuramasafumi/.rubies/ruby-2.7.2/lib/ruby/2.7.0/tempfile.rb:141:in `open'
	 1: from /Users/okuramasafumi/.rubies/ruby-2.7.2/lib/ruby/2.7.0/tempfile.rb:141:in `open'
/Users/okuramasafumi/.rubies/ruby-2.7.2/lib/ruby/2.7.0/tempfile.rb:141:in `initialize': No such file or directory @ rb_sysopen - /var/folders/dh/658jt4r55_1gv2b6fb5hgz740000gn/T/shrine20201230-91997-5sbmiq.png (Errno::ENOENT)
```

### System configuration
**Ruby version**: 2.7.2 or 2.6.6

**Shrine version**: 3.3.0

**Comment by hmistry** [comment]
Hi @okuramasafumi 

Thank you for the sample test - it made it easy to follow and reproduce the failure. On a side note, in future please post questions on Shrine Discourse as we wish to keep Github issues for bug tracking.

The reason for the `versions_compatibility: true` option in the `derivatives` plugin was to handle db records migration from Shrine 2.x to 3.x. It was designed to allow Shrine 3.x to read existing file attachment db records that were created using Shrine 2.x with the `versions` plugin, and then convert it to the new data structure in Shrine 3.x which can then be saved in the new format. It was never intended to allow the user to store derivatives in the old `versions` data structure.

I'd recommend you to only store derivatives in derivatives without the original as the original file is already stored. If you really  want to duplicate the original file in the derivatives, I've provided an example as well.

```rb

# Recommended Solution:
Shrine.plugin :derivatives, 
  create_on_promote: true # no versions_compatibility option need unless you're migrating from Shrine 2.x

class MyUploader < Shrine
  Attacher.derivatives do |original|
    pipeline = ImageProcessing::MiniMagick.source(original)
    size_300 = pipeline.resize_to_fill!(300, 300, &:auto_orient)
    { thumb: size_300 } # only add new derivatives as original already exists
  end
end

# post.image_data
{"id"=>"6f8467c735b6f034b1ff015032a5792c.png",
 "storage"=>"store",
 "metadata"=>{"size"=>95, "mime_type"=>"image/png", "filename"=>"test.png"},  # <=== the original file
 "derivatives"=> #  <=== derivatives of the above original file
  {"thumb"=> 
    {"id"=>"9e3d6904cc38c83239ca61dc505ac39f.png",
     "storage"=>"store",
     "metadata"=>
      {"filename"=>"image_processing20210101-34958-nooedt.png", # <=== the "thumb" derivative
       "size"=>309,
       "mime_type"=>nil}}}}

# ----
# Duplicate the original in derivatives:
Shrine.plugin :derivatives, 
  create_on_promote: true, # no versions_compatibility required

class MyUploader < Shrine
  Attacher.derivatives do |original|
    pipeline = ImageProcessing::MiniMagick.source(original)
    size_300 = pipeline.resize_to_fill!(300, 300, &:auto_orient)
    { original: file, thumb: size_300 } 
  end
end

# post.image_data
{"id"=>"88338e2ee2372d06270441c1b68d24d1.png",
 "storage"=>"store",
 "metadata"=>{"size"=>95, "mime_type"=>"image/png", "filename"=>"test.png"},  # <=== the original file
 "derivatives"=>
  {"original"=>
    {"id"=>"c4141263fd76faee585fc80e9d192b8b.png",
     "storage"=>"store",
     "metadata"=>
      {"size"=>95, "mime_type"=>"image/png", "filename"=>"test.png"}},   # <=== duplicate of original file in derivatives
   "thumb"=>
    {"id"=>"84cdfba8af6b6c9eb9a33b8113c76e50.png",
     "storage"=>"store",
     "metadata"=>
      {"filename"=>"image_processing20210101-35147-17vm3lb.png",   # <=== the thumb file in derivatives
       "size"=>309,
       "mime_type"=>nil}}}}

```

**Comment by okuramasafumi** [comment]
Ah I see, so including original file in the derivatives is not recommended. Thanks!
Should it be described in the documentation? If so, I'll create a PR.

**Comment by hmistry** [comment]
No I don't think it needs to be described in docs as it can cause confusion. Thanks for the thought.

**Comment by janko** [comment]
I think the only way someone will try to include the original file into the derivatives hash is when upgrading from `versions` to `derivatives`, which seems to be your case judging from the `:versions_compatibility` option. And the Upgrading to 3.x guide emphasizes that the original file shouldn't be included, which I also think should suffice.
